// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"orenotorero/handler"
	"orenotorero/repository"
	"orenotorero/service"
)

// Injectors from wire.go:

func InitUserAPI(db *gorm.DB) handler.UserHandler {
	userRepository := repository.NewUserRepostiory(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	return userHandler
}
